# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # set time zone if vagrant-timezone is installed 
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "UTC"
  end
  # the base OS
  config.vm.box = "kalilinux/rolling"
  # set the hostname
  config.vm.guest = :linux
  config.vm.hostname = "kalihax"
  # provision the machine with a shell script
  config.vm.provision "shell", inline: <<-SHELL
  # update repos
  apt-get update
  # install packages - yeah kali repos got good
  apt-get install -y code-oss \
    golang && \
    gdb-peda && \
    gobuster && \
    ffuf && \
    seclists && \
    crackmapexec && \
    bloodhound && \
    covenant-kbx && \
    powershell-empire && \
    starkiller
  # init msf
  msfdb init
  # install evil-winrm
  gem install evil-winrm
  # install nuclei
  GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
  # pips
  pip3 install mitm6
  # git clone all the things 
  mkdir /home/vagrant/opt
  git clone https://github.com/michenriksen/aquatone /home/vagrant/opt/aquatone
  git clone https://github.com/DanMcInerney/xsscrapy /home/vagrant/opt/xsscrapy
  git clone https://github.com/ticarpi/jwt_tool /home/vagrant/opt/jwt_tool
  git clone https://github.com/byt3bl33d3r/ItWasAllADream /home/vagrant/opt/ItWasAllADream
  git clone https://github.com/lgandx/Responder /home/vagrant/opt/Responder
  git clone https://github.com/byt3bl33d3r/DeathStar /home/vagrant/opt/DeathStar
  git clone https://github.com/ly4k/Certipy /home/vagrant/opt/Certipy
SHELL
end
